language: c

matrix:
  include:
  - os: windows
    language: sh
    python: '3.7'
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - python -m pip install --upgrade pip wheel

install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel
  - pip install cpp-coveralls
  
script:
  - mkdir build_mingw && cd build_mingw && cmake -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G"MinGW Makefiles" .. && cmake --build . && mingw32-make unittest_run
  
after_success:
  - coveralls --gcov-options '\-lp'

notifications:
  email: false
