language: c

matrix:
  include:
  - os: windows
  env:
    - OPTIONS="-DCMAKE_SH="CMAKE_SH-NOTFOUND""

install: true

script:
  - mkdir build_mingw && cd build_mingw && cmake ${OPTIONS} -G"MinGW Makefiles" .. && cmake --build .
