language: c

#before_install:
#  - pip install --user cpp-coveralls
  
matrix:
  include:
  - os: windows

install: true

script:
  - mkdir build_mingw && cd build_mingw && cmake -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G"MinGW Makefiles" .. && cmake --build . && mingw32-make unittest_run
